/** 项目用到的 MDI 图标(tree-shaken，由 mdi-svg 解析 mdi-* 名称) */
import {
  mdiAccount,
  mdiAccountCheck,
  mdiAccountOutline,
  mdiAccountPlus,
  mdiAccountQuestion,
  mdiAlertCircle,
  mdiAlertOutline,
  mdiAlphaECircle,
  mdiAngleAcute,
  mdiAppleKeyboardOption,
  mdiApplicationExport,
  mdiApplicationImport,
  mdiArchiveMinusOutline,
  mdiArrowBottomLeft,
  mdiArrowRightThin,
  mdiArrowTopRight,
  mdiAutoFix,
  mdiBackupRestore,
  mdiBluetooth,
  mdiBookOpenOutline,
  mdiCameraOutline,
  mdiCheck,
  mdiCheckAll,
  mdiCheckCircle,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiCircleOutline,
  mdiClipboardCheckOutline,
  mdiClipboardOutline,
  mdiClose,
  mdiCloudOutline,
  mdiCloseCircle,
  mdiCog,
  mdiCogOutline,
  mdiConsole,
  mdiContentCopy,
  mdiController,
  mdiCropFree,
  mdiCursorDefault,
  mdiDelete,
  mdiDeleteOutline,
  mdiDownload,
  mdiDotsHorizontalCircleOutline,
  mdiExclamation,
  mdiExport,
  mdiExpansionCard,
  mdiEye,
  mdiEyeClosed,
  mdiFileExcel,
  mdiFileImageOutline,
  mdiFilePlusOutline,
  mdiFileSearchOutline,
  mdiFitToPageOutline,
  mdiFolderOpenOutline,
  mdiFolderOutline,
  mdiFolderRemoveOutline,
  mdiFormatListBulletedSquare,
  mdiGamepadVariant,
  mdiGamepadVariantOutline,
  mdiHelpCircleOutline,
  mdiHistory,
  mdiImageOutline,
  mdiImageRefreshOutline,
  mdiImageSearchOutline,
  mdiInformationOutline,
  mdiInformationVariant,
  mdiKeyboard,
  mdiKeyboardOffOutline,
  mdiKeyboardOutline,
  mdiKeyboardVariant,
  mdiLanCheck,
  mdiLanConnect,
  mdiLanguageTypescript,
  mdiLaptop,
  mdiLightningBoltOutline,
  mdiLifebuoy,
  mdiListStatus,
  mdiLock,
  mdiLockAlert,
  mdiLockOpenVariant,
  mdiLockReset,
  mdiMagnify,
  mdiMicrosoftXbox,
  mdiMicrosoftWindows,
  mdiMicrosoftOnedrive,
  mdiMinus,
  mdiMonitor,
  mdiMonitorDashboard,
  mdiMouse,
  mdiOpenInNew,
  mdiPaletteOutline,
  mdiPencil,
  mdiPictureInPictureBottomRight,
  mdiPlay,
  mdiPlus,
  mdiPower,
  mdiProgressWrench,
  mdiRadar,
  mdiRefresh,
  mdiRemoteDesktop,
  mdiRestore,
  mdiRestoreAlert,
  mdiRocketLaunch,
  mdiRocketLaunchOutline,
  mdiSecurity,
  mdiShieldCheckOutline,
  mdiShieldSearch,
  mdiServer,
  mdiServerNetwork,
  mdiSpeedometer,
  mdiSteam,
  mdiStoreOutline,
  mdiSwapHorizontal,
  mdiTextBoxSearchOutline,
  mdiTextRecognition,
  mdiToggleSwitchOff,
  mdiToolboxOutline,
  mdiTrayFull,
  mdiTuneVariant,
  mdiVideo,
  mdiVuejs,
  mdiVuetify,
  mdiWindowClose,
  mdiWindowMaximize,
  mdiWindowMinimize,
  mdiWindowRestore,
} from '@mdi/js';

export const mdiPathByName: Record<string, string> = {
  'mdi-account': mdiAccount,
  'mdi-account-check': mdiAccountCheck,
  'mdi-account-outline': mdiAccountOutline,
  'mdi-account-plus': mdiAccountPlus,
  'mdi-account-question': mdiAccountQuestion,
  'mdi-alert-circle': mdiAlertCircle,
  'mdi-alert-outline': mdiAlertOutline,
  'mdi-alpha-e-circle': mdiAlphaECircle,
  'mdi-angle-acute': mdiAngleAcute,
  'mdi-apple-keyboard-option': mdiAppleKeyboardOption,
  'mdi-application-export': mdiApplicationExport,
  'mdi-application-import': mdiApplicationImport,
  'mdi-archive-minus-outline': mdiArchiveMinusOutline,
  'mdi-arrow-bottom-left': mdiArrowBottomLeft,
  'mdi-arrow-right-thin': mdiArrowRightThin,
  'mdi-arrow-top-right': mdiArrowTopRight,
  'mdi-auto-fix': mdiAutoFix,
  'mdi-backup-restore': mdiBackupRestore,
  'mdi-bluetooth': mdiBluetooth,
  'mdi-book-open-outline': mdiBookOpenOutline,
  'mdi-camera-outline': mdiCameraOutline,
  'mdi-check': mdiCheck,
  'mdi-check-all': mdiCheckAll,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-chevron-left': mdiChevronLeft,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-chevron-up': mdiChevronUp,
  'mdi-circle-outline': mdiCircleOutline,
  'mdi-clipboard-check-outline': mdiClipboardCheckOutline,
  'mdi-clipboard-outline': mdiClipboardOutline,
  'mdi-close': mdiClose,
  'mdi-cloud-outline': mdiCloudOutline,
  'mdi-close-circle': mdiCloseCircle,
  'mdi-cog': mdiCog,
  'mdi-cog-outline': mdiCogOutline,
  'mdi-console': mdiConsole,
  'mdi-content-copy': mdiContentCopy,
  'mdi-controller': mdiController,
  'mdi-crop-free': mdiCropFree,
  'mdi-cursor-default': mdiCursorDefault,
  'mdi-delete': mdiDelete,
  'mdi-delete-outline': mdiDeleteOutline,
  'mdi-download': mdiDownload,
  'mdi-dots-horizontal-circle-outline': mdiDotsHorizontalCircleOutline,
  'mdi-exclamation': mdiExclamation,
  'mdi-export': mdiExport,
  'mdi-expansion-card': mdiExpansionCard,
  'mdi-eye': mdiEye,
  'mdi-eye-closed': mdiEyeClosed,
  'mdi-file-excel': mdiFileExcel,
  'mdi-file-image-outline': mdiFileImageOutline,
  'mdi-file-plus-outline': mdiFilePlusOutline,
  'mdi-file-search-outline': mdiFileSearchOutline,
  'mdi-fit-to-page-outline': mdiFitToPageOutline,
  'mdi-folder-open-outline': mdiFolderOpenOutline,
  'mdi-folder-outline': mdiFolderOutline,
  'mdi-folder-remove-outline': mdiFolderRemoveOutline,
  'mdi-format-list-bulleted-square': mdiFormatListBulletedSquare,
  'mdi-gamepad-variant': mdiGamepadVariant,
  'mdi-gamepad-variant-outline': mdiGamepadVariantOutline,
  'mdi-help-circle-outline': mdiHelpCircleOutline,
  'mdi-history': mdiHistory,
  'mdi-image-outline': mdiImageOutline,
  'mdi-image-refresh-outline': mdiImageRefreshOutline,
  'mdi-image-search-outline': mdiImageSearchOutline,
  'mdi-information-outline': mdiInformationOutline,
  'mdi-information-variant': mdiInformationVariant,
  'mdi-keyboard': mdiKeyboard,
  'mdi-keyboard-off-outline': mdiKeyboardOffOutline,
  'mdi-keyboard-outline': mdiKeyboardOutline,
  'mdi-keyboard-variant': mdiKeyboardVariant,
  'mdi-lan-check': mdiLanCheck,
  'mdi-lan-connect': mdiLanConnect,
  'mdi-language-typescript': mdiLanguageTypescript,
  'mdi-laptop': mdiLaptop,
  'mdi-lightning-bolt-outline': mdiLightningBoltOutline,
  'mdi-lifebuoy': mdiLifebuoy,
  'mdi-list-status': mdiListStatus,
  'mdi-lock': mdiLock,
  'mdi-lock-alert': mdiLockAlert,
  'mdi-lock-open-variant': mdiLockOpenVariant,
  'mdi-lock-reset': mdiLockReset,
  'mdi-magnify': mdiMagnify,
  'mdi-microsoft-xbox': mdiMicrosoftXbox,
  'mdi-microsoft-windows': mdiMicrosoftWindows,
  'mdi-microsoft-onedrive': mdiMicrosoftOnedrive,
  'mdi-minus': mdiMinus,
  'mdi-monitor': mdiMonitor,
  'mdi-monitor-dashboard': mdiMonitorDashboard,
  'mdi-mouse': mdiMouse,
  'mdi-open-in-new': mdiOpenInNew,
  'mdi-palette-outline': mdiPaletteOutline,
  'mdi-pencil': mdiPencil,
  'mdi-picture-in-picture-bottom-right': mdiPictureInPictureBottomRight,
  'mdi-play': mdiPlay,
  'mdi-plus': mdiPlus,
  'mdi-power': mdiPower,
  'mdi-progress-wrench': mdiProgressWrench,
  'mdi-radar': mdiRadar,
  'mdi-refresh': mdiRefresh,
  'mdi-remote-desktop': mdiRemoteDesktop,
  'mdi-restore': mdiRestore,
  'mdi-restore-alert': mdiRestoreAlert,
  'mdi-rocket-launch': mdiRocketLaunch,
  'mdi-rocket-launch-outline': mdiRocketLaunchOutline,
  'mdi-security': mdiSecurity,
  'mdi-shield-check-outline': mdiShieldCheckOutline,
  'mdi-shield-search': mdiShieldSearch,
  'mdi-server': mdiServer,
  'mdi-server-network': mdiServerNetwork,
  'mdi-speedometer': mdiSpeedometer,
  'mdi-steam': mdiSteam,
  'mdi-store-outline': mdiStoreOutline,
  'mdi-swap-horizontal': mdiSwapHorizontal,
  'mdi-text-box-search-outline': mdiTextBoxSearchOutline,
  'mdi-text-recognition': mdiTextRecognition,
  'mdi-toggle-switch-off': mdiToggleSwitchOff,
  'mdi-toolbox-outline': mdiToolboxOutline,
  'mdi-tray-full': mdiTrayFull,
  'mdi-tune-variant': mdiTuneVariant,
  'mdi-video': mdiVideo,
  'mdi-vuejs': mdiVuejs,
  'mdi-vuetify': mdiVuetify,
  'mdi-window-close': mdiWindowClose,
  'mdi-window-maximize': mdiWindowMaximize,
  'mdi-window-minimize': mdiWindowMinimize,
  'mdi-window-restore': mdiWindowRestore,
};

/** 将 mdi-* 名称解析为 @mdi/js SVG path */
export function resolveMdiIcon(icon: string | undefined): string | undefined {
  if (icon?.startsWith('mdi-')) {
    return mdiPathByName[icon] ?? icon;
  }
  return icon;
}
