/** 项目用到的 MDI 图标(tree-shaken，由 mdi-svg 解析 mdi-* 名称) */
import {
  mdiAccount,
  mdiAccountCheck,
  mdiAccountOutline,
  mdiAccountPlus,
  mdiAccountQuestion,
  mdiAlphaECircle,
  mdiAppleKeyboardOption,
  mdiArchiveMinusOutline,
  mdiArrowBottomLeft,
  mdiArrowRightThin,
  mdiArrowTopRight,
  mdiBackupRestore,
  mdiBook,
  mdiBookMultiple,
  mdiCheck,
  mdiCheckCircle,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiClipboardCheckOutline,
  mdiClipboardOutline,
  mdiClose,
  mdiCloseCircle,
  mdiCog,
  mdiCogOutline,
  mdiConsole,
  mdiContentCopy,
  mdiDelete,
  mdiExclamation,
  mdiExport,
  mdiEye,
  mdiEyeClosed,
  mdiFileExcel,
  mdiFitToPageOutline,
  mdiFolderOutline,
  mdiFolderRemoveOutline,
  mdiFormatListBulletedSquare,
  mdiGamepadVariant,
  mdiGamepadVariantOutline,
  mdiInformationVariant,
  mdiKeyboardVariant,
  mdiLanConnect,
  mdiLanguageTypescript,
  mdiLaptop,
  mdiLightningBoltOutline,
  mdiListStatus,
  mdiLock,
  mdiLockAlert,
  mdiLockOpenVariant,
  mdiLockReset,
  mdiMagnify,
  mdiMicrosoftXbox,
  mdiMinus,
  mdiMonitor,
  mdiPencil,
  mdiPlay,
  mdiPlus,
  mdiRefresh,
  mdiRemoteDesktop,
  mdiRestore,
  mdiRocketLaunch,
  mdiRocketLaunchOutline,
  mdiSecurity,
  mdiServer,
  mdiServerNetwork,
  mdiStarFourPoints,
  mdiSteam,
  mdiToolboxOutline,
  mdiTools,
  mdiTuneVariant,
  mdiVuejs,
  mdiVuetify,
  mdiWindowClose,
  mdiWindowMaximize,
  mdiWindowMinimize,
  mdiWindowRestore,
} from '@mdi/js';

export const mdiPathByName: Record<string, string> = {
  'mdi-account': mdiAccount,
  'mdi-account-check': mdiAccountCheck,
  'mdi-account-outline': mdiAccountOutline,
  'mdi-account-plus': mdiAccountPlus,
  'mdi-account-question': mdiAccountQuestion,
  'mdi-alpha-e-circle': mdiAlphaECircle,
  'mdi-apple-keyboard-option': mdiAppleKeyboardOption,
  'mdi-archive-minus-outline': mdiArchiveMinusOutline,
  'mdi-arrow-bottom-left': mdiArrowBottomLeft,
  'mdi-arrow-right-thin': mdiArrowRightThin,
  'mdi-arrow-top-right': mdiArrowTopRight,
  'mdi-backup-restore': mdiBackupRestore,
  'mdi-book': mdiBook,
  'mdi-book-multiple': mdiBookMultiple,
  'mdi-check': mdiCheck,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-chevron-left': mdiChevronLeft,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-chevron-up': mdiChevronUp,
  'mdi-clipboard-check-outline': mdiClipboardCheckOutline,
  'mdi-clipboard-outline': mdiClipboardOutline,
  'mdi-close': mdiClose,
  'mdi-close-circle': mdiCloseCircle,
  'mdi-cog': mdiCog,
  'mdi-cog-outline': mdiCogOutline,
  'mdi-console': mdiConsole,
  'mdi-content-copy': mdiContentCopy,
  'mdi-delete': mdiDelete,
  'mdi-exclamation': mdiExclamation,
  'mdi-export': mdiExport,
  'mdi-eye': mdiEye,
  'mdi-eye-closed': mdiEyeClosed,
  'mdi-file-excel': mdiFileExcel,
  'mdi-fit-to-page-outline': mdiFitToPageOutline,
  'mdi-folder-outline': mdiFolderOutline,
  'mdi-folder-remove-outline': mdiFolderRemoveOutline,
  'mdi-format-list-bulleted-square': mdiFormatListBulletedSquare,
  'mdi-gamepad-variant': mdiGamepadVariant,
  'mdi-gamepad-variant-outline': mdiGamepadVariantOutline,
  'mdi-information-variant': mdiInformationVariant,
  'mdi-keyboard-variant': mdiKeyboardVariant,
  'mdi-lan-connect': mdiLanConnect,
  'mdi-language-typescript': mdiLanguageTypescript,
  'mdi-laptop': mdiLaptop,
  'mdi-lightning-bolt-outline': mdiLightningBoltOutline,
  'mdi-list-status': mdiListStatus,
  'mdi-lock': mdiLock,
  'mdi-lock-alert': mdiLockAlert,
  'mdi-lock-open-variant': mdiLockOpenVariant,
  'mdi-lock-reset': mdiLockReset,
  'mdi-magnify': mdiMagnify,
  'mdi-microsoft-xbox': mdiMicrosoftXbox,
  'mdi-minus': mdiMinus,
  'mdi-monitor': mdiMonitor,
  'mdi-pencil': mdiPencil,
  'mdi-play': mdiPlay,
  'mdi-plus': mdiPlus,
  'mdi-refresh': mdiRefresh,
  'mdi-remote-desktop': mdiRemoteDesktop,
  'mdi-restore': mdiRestore,
  'mdi-rocket-launch': mdiRocketLaunch,
  'mdi-rocket-launch-outline': mdiRocketLaunchOutline,
  'mdi-security': mdiSecurity,
  'mdi-server': mdiServer,
  'mdi-server-network': mdiServerNetwork,
  'mdi-star-four-points': mdiStarFourPoints,
  'mdi-steam': mdiSteam,
  'mdi-toolbox-outline': mdiToolboxOutline,
  'mdi-tools': mdiTools,
  'mdi-tune-variant': mdiTuneVariant,
  'mdi-vuejs': mdiVuejs,
  'mdi-vuetify': mdiVuetify,
  'mdi-window-close': mdiWindowClose,
  'mdi-window-maximize': mdiWindowMaximize,
  'mdi-window-minimize': mdiWindowMinimize,
  'mdi-window-restore': mdiWindowRestore,
};

/** 将 mdi-* 名称解析为 @mdi/js SVG path */
export function resolveMdiIcon(icon: string | undefined): string | undefined {
  if (icon?.startsWith('mdi-')) {
    return mdiPathByName[icon] ?? icon;
  }
  return icon;
}
